import Head from 'next/head';
import styles from '../../styles/Home.module.css';

export default function DefaultLayout({ children }: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>{children}</main>
      <footer className={styles.footer}>&copy; StubbyDigits, {new Date().getFullYear()}</footer>
    </div>
  );
}
